counties = ['Agder', 
            'Akershus', 
            'Buskerud', 
            'Finnmark', 
            'Innlandet', 
            'Møre og Romsdal', 
            'Nordland', 
            'Oslo', 
            'Rogaland', 
            'Telemark', 
            'Troms', 
            'Trøndelag', 
            'Vestfold', 
            'Vestland', 
            'Østfold']
